"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "Translation/**/*.json",
    "translation": "Translation/%original_path%/%two_letters_code%_%original_file_name%",
    "ignore": [
      "Translation/001/",
      "Translation/002/",
      "Translation/004/"
    ],
  },
]